config/routes.rb
BoiseMeetup::Application.routes.draw do
  resources :servers

end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  skip_before_action :verify_authenticity_token

  def index
    @servers = Rails.cache.fetch(view_context.cache_key_for_servers) do
      all_servers = Server.all
      all_servers.to_a
    end
    respond_with @servers
  end

  def show
  end

  def create
    @server = Server.new(server_params)
    if @server.save
      #Rails.cache.delete('servers')
      render action: 'show', status: :created, location: @server
    else
      render json: @server.errors, status: :unprocessable_entity
    end
  end

  private
    def set_server
      @server = Server.find(params[:id])
    end

    def server_params
      params.permit(:name, :ip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
  def cache_key_for_servers
    count          = Server.count
    max_updated_at = Server.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "servers/all-#{count}-#{max_updated_at}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoiseMeetup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.ip %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @server.ip %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>